// js/states.js
//
// Per-jurisdiction Vehicle Bill of Sale data.
// 50 states + DC. Sources cited per entry on the last update; verify with
// the linked dmvUrl before relying on details for a real transaction.

export const STATES = {
  AL: {
    name: 'Alabama',
    abbr: 'AL',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 20,
    dmvUrl: 'https://www.revenue.alabama.gov/division/motor-vehicle/',
    notes: 'Title application within 20 days. AL does not publish a single private-sale BoS form; meeting Rule 810-5-1-.246 minimums is sufficient and notarization is not required.',
    sources: [
      'https://www.revenue.alabama.gov/division/motor-vehicle/',
      'https://www.revenue.alabama.gov/admin-rules/bill-of-sale-invoice-or-other-sales-document-minimum-requirements/',
    ],
  },
  AK: {
    name: 'Alaska',
    abbr: 'AK',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://dmv.alaska.gov/',
    notes: 'Title application within 30 days. No state BoS form required, and notarization is not required for the BoS itself.',
    sources: [
      'https://dmv.alaska.gov/vehicle-services/selling-a-vehicle-in-alaska/',
    ],
  },
  AZ: {
    name: 'Arizona',
    abbr: 'AZ',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: '38-1306',
    filingDeadlineDays: 15,
    dmvUrl: 'https://azdot.gov/mvd',
    notes: 'Form 38-1306 (Title Transfer Bill of Sale) requires notarization when used in lieu of a paper title. Buyer titles within 15 days.',
    sources: [
      'https://azdot.gov/mvd-doc-lib/title-transfer-bill-sale',
    ],
  },
  AR: {
    name: 'Arkansas',
    abbr: 'AR',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: '10-313',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.dfa.arkansas.gov/office/motor-vehicle/',
    notes: 'Form 10-313 (BoS / Odometer / POA). Buyer titles within 30 days; notarization is not mandatory.',
    sources: [
      'https://www.dfa.arkansas.gov/wp-content/uploads/TitleAssignmentMileageDisclosureBillofSale.pdf',
    ],
  },
  CA: {
    name: 'California',
    abbr: 'CA',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'REG 135',
    filingDeadlineDays: 10,
    dmvUrl: 'https://www.dmv.ca.gov/',
    notes: 'REG 135 is the official BoS and notarization is not required. Ownership change must be reported to DMV within 10 days.',
    sources: [
      'https://www.dmv.ca.gov/portal/file/bill-of-sale-reg-135-pdf',
    ],
  },
  CO: {
    name: 'Colorado',
    abbr: 'CO',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'DR 2173',
    filingDeadlineDays: 60,
    dmvUrl: 'https://dmv.colorado.gov/',
    notes: 'DR 2173 is the secure BoS and covers odometer disclosure. Registration within 60 days; late fees $25/month thereafter.',
    sources: [
      'https://dmv.colorado.gov/buying-and-selling',
    ],
  },
  CT: {
    name: 'Connecticut',
    abbr: 'CT',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'H-31',
    filingDeadlineDays: null,
    dmvUrl: 'https://portal.ct.gov/dmv',
    notes: 'Form H-31 is the official BoS, used with the assigned title for new registration. No notarization required and no clear statutory in-state filing deadline confirmed.',
    sources: [
      'https://portal.ct.gov/dmv/vehicle-services/get-bill-of-sale',
      'https://portal.ct.gov/-/media/dmv/20/29/h31pdf.pdf',
    ],
  },
  DE: {
    name: 'Delaware',
    abbr: 'DE',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://dmv.de.gov/',
    notes: 'DE does not publish a private-sale BoS form. Title transfer within 30 days; titles do not require notarization.',
    sources: [
      'https://dmv.de.gov/VehicleServices/titles/index.shtml?dc=ve_title_transfer',
    ],
  },
  FL: {
    name: 'Florida',
    abbr: 'FL',
    honorific: 'State',
    notary: 'recommended',
    odometerThresholdYears: 20,
    bosFormName: 'HSMV 82050',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.flhsmv.gov/',
    notes: 'HSMV 82050 is the official BoS; notarization is recommended but no longer required. Title application within 30 days; $20 penalty after.',
    sources: [
      'https://www.flhsmv.gov/pdf/forms/82050.pdf',
    ],
  },
  GA: {
    name: 'Georgia',
    abbr: 'GA',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'T-7',
    filingDeadlineDays: 7,
    dmvUrl: 'https://dor.georgia.gov/motor-vehicles',
    notes: 'Form T-7 is the GA DOR BoS with odometer disclosure. 7-day title/registration window at the county tag office; 10% TAVT late penalty after.',
    sources: [
      'https://dor.georgia.gov/t-7-bill-sale',
    ],
  },
  HI: {
    name: 'Hawaii',
    abbr: 'HI',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'CS-L(MVR)40',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.honolulu.gov/csd/vehicle-ownership-transfer/',
    notes: 'County-administered; CS-L(MVR)40 is used across counties. 30-day buyer title transfer or $50 penalty.',
    sources: [
      'https://www.honolulu.gov/csd/vehicle-ownership-transfer/',
    ],
  },
  ID: {
    name: 'Idaho',
    abbr: 'ID',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'ITD 3738',
    filingDeadlineDays: 30,
    dmvUrl: 'https://itd.idaho.gov/dmv/registrations-plates-titles/vehicle-titles/',
    notes: 'Form ITD 3738. New owner has 30 days; title application requires a notarized signature only if mailed (not for in-person filing).',
    sources: [
      'https://itd.idaho.gov/wp-content/uploads/2025/03/3738.pdf',
    ],
  },
  IL: {
    name: 'Illinois',
    abbr: 'IL',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 20,
    dmvUrl: 'https://www.ilsos.gov/departments/vehicles/title-and-registration.html',
    notes: 'IL Secretary of State does not publish a dedicated BoS form. Title assignment generally not notarized; RUT-50 private-party tax due within 30 days.',
    sources: [
      'https://www.ilsos.gov/departments/vehicles/title-and-registration/apply.html',
    ],
  },
  IN: {
    name: 'Indiana',
    abbr: 'IN',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'State Form 44237',
    filingDeadlineDays: 45,
    dmvUrl: 'https://www.in.gov/bmv/titles/buying-and-selling/',
    notes: 'BMV State Form 44237. Title application within 45 days; the BoS itself does not require notarization.',
    sources: [
      'https://forms.in.gov/Download.aspx?id=5521',
    ],
  },
  IA: {
    name: 'Iowa',
    abbr: 'IA',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://iowadot.gov/registration-plates/buy-sell-vehicles/how-sell-vehicle',
    notes: 'BoS required for all title transfers; no statewide DOT-published form (counties publish their own). 30-day retitle window; notarization typically not required.',
    sources: [
      'https://iowadot.gov/registration-plates/buy-sell-vehicles/how-sell-vehicle',
    ],
  },
  KS: {
    name: 'Kansas',
    abbr: 'KS',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'TR-312',
    filingDeadlineDays: 60,
    dmvUrl: 'https://www.ksrevenue.gov/dovtitle.html',
    notes: 'Form TR-312. KS DOR explicitly states most BoS / title assignments completed in-state do not need notarization; buyer titles within 60 days.',
    sources: [
      'https://www.ksrevenue.gov/pdf/tr312.pdf',
    ],
  },
  KY: {
    name: 'Kentucky',
    abbr: 'KY',
    honorific: 'Commonwealth',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 15,
    dmvUrl: 'https://drive.ky.gov/Vehicles/Pages/Vehicle-Titling.aspx',
    notes: 'Seller signs title in presence of a notary; TC 96-182 (title application) must be signed and notarized, otherwise the buyer is taxed on NADA high retail. No standalone BoS form confirmed via .gov.',
    sources: [
      'https://drive.ky.gov/Vehicles/Pages/Vehicle-Titling.aspx',
      'https://transportation.ky.gov/Organizational-Resources/Forms/TC%2096-182.pdf',
    ],
  },
  LA: {
    name: 'Louisiana',
    abbr: 'LA',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 40,
    dmvUrl: 'https://www.expresslane.org/vehicles/title-and-registration/used-title-registration/',
    notes: 'Original notarized BoS / invoice required for OMV title transfer. Application within 40 days (sales tax also due by day 40).',
    sources: [
      'https://www.expresslane.org/vehicles/title-and-registration/used-title-registration/',
    ],
  },
  ME: {
    name: 'Maine',
    abbr: 'ME',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'Motor Vehicle Bill of Sale',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.maine.gov/sos/bmv/vehicles/titles',
    notes: 'BMV publishes a Motor Vehicle Bill of Sale PDF (no numeric code). Standard transfers do not need notarization; 30-day title application expectation per statute.',
    sources: [
      'https://www.maine.gov/sos/sites/maine.gov.sos/files/content/assets/Motor-20Vehicle-20Bill-20of-20Sale.pdf',
    ],
  },
  MD: {
    name: 'Maryland',
    abbr: 'MD',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'VR-181',
    filingDeadlineDays: null,
    dmvUrl: 'https://mva.maryland.gov/title-registration/buying-selling-or-gifting-vehicle/buying-vehicle',
    notes: 'Form VR-181. Notarization triggered only when buyer claims sale price below NADA book value on a vehicle <7 years old; no clear in-state private-sale filing deadline confirmed.',
    sources: [
      'https://mva.maryland.gov/Documents/VR-181.pdf',
    ],
  },
  MA: {
    name: 'Massachusetts',
    abbr: 'MA',
    honorific: 'Commonwealth',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 10,
    dmvUrl: 'https://www.mass.gov/orgs/massachusetts-registry-of-motor-vehicles',
    notes: 'RMV does not publish an official BoS form. Title within 10 days of purchase; no notarization required.',
    sources: [
      'https://www.mass.gov/how-to/apply-for-a-registration-and-title-for-a-vehicle-purchased-from-an-individual',
    ],
  },
  MI: {
    name: 'Michigan',
    abbr: 'MI',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'TR-207',
    filingDeadlineDays: 15,
    dmvUrl: 'https://www.michigan.gov/sos',
    notes: 'MI SOS publishes optional BoS form TR-207. 15-day title transfer or $15 late fee.',
    sources: [
      'https://www.michigan.gov/sos/-/media/Project/Websites/sos/24lawensn/tr207.pdf',
    ],
  },
  MN: {
    name: 'Minnesota',
    abbr: 'MN',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 10,
    dmvUrl: 'https://dps.mn.gov/divisions/dvs',
    notes: 'DVS does not publish a BoS form. Seller files Notice of Sale within 10 days; buyer title application due within 20 days of assignment per Minn. Stat. 168A.10.',
    sources: [
      'https://dps.mn.gov/divisions/dvs/vehicle/vehicle-titles/vehicle-title-transfer',
    ],
  },
  MS: {
    name: 'Mississippi',
    abbr: 'MS',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.dor.ms.gov/motor-vehicle',
    notes: 'DOR does not publish a BoS form for routine sales. Buyers register within 30 business days; $250 penalty.',
    sources: [
      'https://www.dor.ms.gov/motor-vehicle/motor-vehicle-frequently-asked-questions',
    ],
  },
  MO: {
    name: 'Missouri',
    abbr: 'MO',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'Form 1957',
    filingDeadlineDays: 30,
    dmvUrl: 'https://dor.mo.gov/motor-vehicle/',
    notes: 'Form 1957 is the official BoS; notarization required only for rebuilt-vehicle major component parts or when DOR specifically requests it. Sellers file Notice of Sale or 1957 within 30 days.',
    sources: [
      'https://dor.mo.gov/forms/1957.pdf',
    ],
  },
  MT: {
    name: 'Montana',
    abbr: 'MT',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'MV-24',
    filingDeadlineDays: 60,
    dmvUrl: 'https://dojmt.gov/driving/',
    notes: 'MVD form MV-24; notarization required only in specific scenarios (out-of-state dealer sales, untitled campers). New residents and purchasers have 60 days.',
    sources: [
      'https://dojmt.gov/driving/buying-or-selling-a-vehicle/',
    ],
  },
  NE: {
    name: 'Nebraska',
    abbr: 'NE',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://dmv.nebraska.gov',
    notes: 'DMV publishes a sample BoS but no mandatory form. Buyer obtains title within 30 days; standard BoS does not require notarization.',
    sources: [
      'https://dmv.nebraska.gov/dvr/title/transfer-ownership',
    ],
  },
  NV: {
    name: 'Nevada',
    abbr: 'NV',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'VP 104',
    filingDeadlineDays: 30,
    dmvUrl: 'https://dmv.nv.gov',
    notes: 'Form VP 104 is the official BoS. Buyers register within 30 days; the BoS does not require notarization (POA does).',
    sources: [
      'https://dmv.nv.gov/pdfforms/vp104.pdf',
    ],
  },
  NH: {
    name: 'New Hampshire',
    abbr: 'NH',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: null,
    dmvUrl: 'https://www.dmv.nh.gov',
    notes: 'Per RSA 261:148 III, BoS must include date of sale and signed names/legal addresses (no PO Box); notarization explicitly not required. Vehicles 15+ MY old are title-exempt.',
    sources: [
      'https://www.dmv.nh.gov/bill-sale',
    ],
  },
  NJ: {
    name: 'New Jersey',
    abbr: 'NJ',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 10,
    dmvUrl: 'https://www.nj.gov/mvc',
    notes: 'MVC does not publish a single official BoS form. Title transfers within 10 working days or $25 penalty; notarized BoS required for pre-owned vehicles without a title.',
    sources: [
      'https://www.nj.gov/mvc/vehicles/transowner.htm',
    ],
  },
  NM: {
    name: 'New Mexico',
    abbr: 'NM',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'MVD-10009',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.mvd.newmexico.gov',
    notes: 'MVD-10009 does not require notarization. In-state title transfer within 30 days.',
    sources: [
      'https://realfile.tax.newmexico.gov/mvd10009.pdf',
    ],
  },
  NY: {
    name: 'New York',
    abbr: 'NY',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'MV-912',
    filingDeadlineDays: null,
    dmvUrl: 'https://dmv.ny.gov',
    notes: 'MV-912 BoS and original NY title transfer do not require notarization. DMV mails new title after buyer registers.',
    sources: [
      'https://dmv.ny.gov/forms/mv912.pdf',
    ],
  },
  NC: {
    name: 'North Carolina',
    abbr: 'NC',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 28,
    dmvUrl: 'https://www.ncdot.gov/dmv',
    notes: 'No state BoS form (MVR-181 is damage disclosure, not BoS). Title assignment + MVR-1 application must be notarized; buyer transfers within 28 days.',
    sources: [
      'https://www.ncdot.gov/dmv/title-registration/vehicle/Pages/title-transfer.aspx',
    ],
  },
  ND: {
    name: 'North Dakota',
    abbr: 'ND',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: 'SFN 2888',
    filingDeadlineDays: null,
    dmvUrl: 'https://www.dot.nd.gov/motor-vehicle',
    notes: 'SFN 2888 (Seller’s Certificate / BoS); notarization required for untitled vehicles and lien sales. Seller delivers endorsed title within 15 days.',
    sources: [
      'https://www.dot.nd.gov/forms/sfn02888.pdf',
    ],
  },
  OH: {
    name: 'Ohio',
    abbr: 'OH',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.bmv.ohio.gov',
    notes: 'OH BMV does not issue a BoS. Seller’s title-assignment signature must be notarized; buyer applies for title within 30 days or pays a late fee.',
    sources: [
      'https://www.bmv.ohio.gov/titles-new.aspx',
    ],
  },
  OK: {
    name: 'Oklahoma',
    abbr: 'OK',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://oklahoma.gov/service/all-services/auto-vehicle.html',
    notes: 'Service OK requires notarized title assignment; no generic state BoS form (Form 718 is for electronic-title transfers; 722-1 is purchase-price declaration). Buyer titles within 30 days.',
    sources: [
      'https://oklahoma.gov/service/all-services/auto-vehicle/vehicle-titles.html',
    ],
  },
  OR: {
    name: 'Oregon',
    abbr: 'OR',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: '735-501',
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.oregon.gov/odot/dmv',
    notes: 'Form 735-501 does not require notarization. Buyer titles within 30 days; seller notifies DMV within 10 days.',
    sources: [
      'https://www.oregon.gov/odot/forms/dmv/501fill.pdf',
    ],
  },
  PA: {
    name: 'Pennsylvania',
    abbr: 'PA',
    honorific: 'Commonwealth',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: 'MV-4ST',
    filingDeadlineDays: 20,
    dmvUrl: 'https://www.dmv.pa.gov',
    notes: 'Seller’s title signature must be notarized. MV-4ST title/registration packet must reach PennDOT within 20 days of notarization.',
    sources: [
      'https://www.pa.gov/agencies/dmv/vehicle-services/title-and-registration/buying-or-selling-a-vehicle',
    ],
  },
  RI: {
    name: 'Rhode Island',
    abbr: 'RI',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://dmv.ri.gov',
    notes: 'RI DMV publishes only a sample BoS. The BoS does not need notarization, but a non-immediate-family gift letter does; 30-day private-party title filing.',
    sources: [
      'https://dmv.ri.gov/registrations-plates-titles/titles',
    ],
  },
  SC: {
    name: 'South Carolina',
    abbr: 'SC',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'Form 4031',
    filingDeadlineDays: 45,
    dmvUrl: 'https://dmv.sc.gov',
    notes: 'Form 4031 does not require notarization. New owners register within 45 days.',
    sources: [
      'https://www.scdmvonline.com/-/media/Forms/4031.ashx',
    ],
  },
  SD: {
    name: 'South Dakota',
    abbr: 'SD',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'MV-016',
    filingDeadlineDays: 45,
    dmvUrl: 'https://dor.sd.gov/individuals/motor-vehicle/',
    notes: 'BoS not required by state but recommended. Buyer titles/registers with the county treasurer within 45 days.',
    sources: [
      'https://dor.sd.gov/individuals/motor-vehicle/cars-trucks-vans/',
    ],
  },
  TN: {
    name: 'Tennessee',
    abbr: 'TN',
    honorific: 'State',
    notary: 'recommended',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.tn.gov/revenue/title-and-registration.html',
    notes: 'No state-issued BoS form. Buyer files at county clerk within 30 days; notarized BoS required for out-of-state titles (KY exempt).',
    sources: [
      'https://www.tn.gov/revenue/title-and-registration/forms.html',
    ],
  },
  TX: {
    name: 'Texas',
    abbr: 'TX',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle',
    notes: 'TX does not have an official BoS form (130-U is the title application) and the title does not require notarization. Buyer titles within 30 days; gift transfers (14-317) require notarization.',
    sources: [
      'https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle',
    ],
  },
  UT: {
    name: 'Utah',
    abbr: 'UT',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: 'TC-843',
    filingDeadlineDays: 60,
    dmvUrl: 'https://dmv.utah.gov/titles-overview/titles/',
    notes: 'Form TC-843 (State Tax Commission) does not require notarization. Buyer titles within 60 days; seller delivers title within 48 hours.',
    sources: [
      'https://tax.utah.gov/forms/current/tc-843.pdf',
    ],
  },
  VT: {
    name: 'Vermont',
    abbr: 'VT',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: 'VT-005',
    filingDeadlineDays: null,
    dmvUrl: 'https://dmv.vermont.gov/tax-title/vehicle-title',
    notes: 'Form VT-005 (combined BoS & Odometer Disclosure) does not require notarization. Purchase & Use Tax due at registration; no clear in-state private-sale filing deadline.',
    sources: [
      'https://dmv.vermont.gov/sites/dmv/files/documents/VT-005-Bill_of_Sale_ODS.pdf',
    ],
  },
  VA: {
    name: 'Virginia',
    abbr: 'VA',
    honorific: 'Commonwealth',
    notary: 'recommended',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://www.dmv.virginia.gov/vehicles/title',
    notes: 'VA DMV does not publish an official BoS form (VSA 17A is the title application). Buyer titles within 30 days.',
    sources: [
      'https://www.dmv.virginia.gov/vehicles/title',
      'https://www.dmv.virginia.gov/vehicles/buy-sell',
    ],
  },
  WA: {
    name: 'Washington',
    abbr: 'WA',
    honorific: 'State',
    notary: 'recommended',
    odometerThresholdYears: 20,
    bosFormName: 'TD-420-065',
    filingDeadlineDays: 15,
    dmvUrl: 'https://dol.wa.gov/vehicles-and-boats/vehicles/buying-and-selling-vehicle/buy-and-register-vehicle',
    notes: 'TD-420-065 BoS does not require notarization itself, but companion title application TD-420-001 must be signed before a notary or agent. Buyer titles within 15 days.',
    sources: [
      'https://dol.wa.gov/forms/view/420065/download?inline=',
    ],
  },
  WV: {
    name: 'West Virginia',
    abbr: 'WV',
    honorific: 'State',
    notary: 'required',
    odometerThresholdYears: 20,
    bosFormName: 'DMV-7-TR',
    filingDeadlineDays: 30,
    dmvUrl: 'https://transportation.wv.gov/DMV/Vehicle-Services/Titles/Pages/default.aspx',
    notes: 'Form DMV-7-TR is the official BoS and must be notarized for both buyer and seller. Buyer titles within 30 days or $15 late fee.',
    sources: [
      'https://transportation.wv.gov/DMV/Vehicle-Services/Titles/Pages/default.aspx',
    ],
  },
  WI: {
    name: 'Wisconsin',
    abbr: 'WI',
    honorific: 'State',
    notary: 'not_required',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 30,
    dmvUrl: 'https://wisconsindot.gov/Pages/dmv/vehicles/sll-jnk-vhcl/sellyourvehicle.aspx',
    notes: 'WI does not require or issue an official BoS and no notarization is required. Buyer titles via Form MV1 within 30 days; seller files Seller Notification within 30 days.',
    sources: [
      'https://wisconsindot.gov/Pages/dmv/vehicles/sll-jnk-vhcl/sellyourvehicle.aspx',
    ],
  },
  WY: {
    name: 'Wyoming',
    abbr: 'WY',
    honorific: 'State',
    notary: 'optional',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 45,
    dmvUrl: 'https://www.dot.state.wy.us/home/dmv.html',
    notes: 'No statewide BoS form (titles handled by county clerks); BoS notarization not required for validity, but a notarized BoS lets the buyer drive up to 60 days while waiting for title. Sales tax due within 65 days.',
    sources: [
      'https://www.dot.state.wy.us/home/dmv.html',
    ],
  },
  DC: {
    name: 'District of Columbia',
    abbr: 'DC',
    honorific: '',
    notary: 'recommended',
    odometerThresholdYears: 20,
    bosFormName: null,
    filingDeadlineDays: 15,
    dmvUrl: 'https://dmv.dc.gov/service/dmv-vehicle-titles',
    notes: 'DC does not issue an official BoS form. Vehicle Title Application (DMV-CTA-001) must be signed before a notary; buyer applies for title within 15 days.',
    sources: [
      'https://dmv.dc.gov/service/dmv-vehicle-titles',
    ],
  },
};

export const STATE_LIST = Object.values(STATES).sort((a, b) => a.name.localeCompare(b.name));

export function getState(abbr) {
  return STATES[String(abbr || '').toUpperCase()] || STATES.VA;
}
